#!/usr/bin/env Rscript

# detect script being run by snakemake
# if so, make a mock commandArgs function
if ('snakemake' %in% ls()) {
    logfile <- snakemake@log[[1]]
    con <- file(logfile, 'w')
    sink(con, type='output')
    sink(con, type='message')

    commandArgs <- function(...) unlist(c(
        snakemake@output[1],     # output table
        snakemake@input[1],      # EID metadata from Roadmap 
        snakemake@input[2:length(snakemake@input)]  # variable sized list of esummary RDAs
    ))
    cat('Got command line arguments from snakemake:\n')
    print(commandArgs())
}

args <- commandArgs(trailingOnly=TRUE)
if (length(args) < 3) {
    cat('IMPORTANT: esummaryX.rda filenames must contain all relevant info\n')
    cat('about that sample: ENCODE ID, bin size, and number of quantiles.\n')
    cat('Currently, the format is:\n')
    cat('    [ENCODE_ID].tiled_[binsize]binsize_[nquantiles]quantiles.SUMMARY.rda\n')
    cat('\n')
    cat('encode_metadata.csv is the metadata file provided by ENCODE.\n')
    cat('It is the first file in the full file manifest generated by the\n')
    cat('website\'s data matrix.\n')
    stop("usage: make_encode_replichip_enrichment_table.R out.csv encode_metadata.csv esummary1.rda [ esummary2.rda ... esummaryN.rda ]")
}

out.csv <- args[1]
meta.csv <- args[2]
esummary.rdas <- args[-(1:2)]

if (file.exists(out.csv))
    stop(paste('output file', out.csv, 'already exists, please delete it first'))

library(data.table)

meta <- fread(meta.csv)
setkey(meta, `File accession`)

fs <- basename(esummary.rdas)
enc.id <- substr(fs, 1, 11)

dotsplit <- strsplit(fs, '.', fixed=TRUE)

binsize <- sub('binsize', '', sapply(strsplit(sapply(dotsplit, `[`, 2), '_'), `[`, 2))
nquantiles <- sub('quantiles', '', sapply(strsplit(sapply(dotsplit, `[`, 2), '_'), `[`, 3))


full.table <- do.call(rbind, lapply(1:length(esummary.rdas), function(i) {
    x <- get(load(esummary.rdas[i]))
    x <- x[rownames(x) != 'outside' & rownames(x) != 'excluded',]
    x <- x[order(as.integer(rownames(x))),]
    data.table(#filename=fs[i],
        enc_id=enc.id[i], meta[enc.id[i],.(`Biosample term name`, `Biosample term id`, `Biosample type`, `Experiment accession`, `Assay`)],
        binsize=binsize[i], nquantiles=nquantiles[i],
        quantile=as.integer(rownames(x)), x)
}))

fwrite(full.table, file=out.csv)
